name: "\U0001F41E Issue report"
description: Report a issue to help us improve.
labels: ['bug: pending triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this form to help us improve. Please read the following before you start filling out the form.
        EdgeLab Model Zoo accepts feedback on the following issues:
        - Model file error, cannot be downloaded
        - Model inference errors, abnormal inference results
        - Wrong test parameters, license issues, etc.
        For issues such as errors in the runtime code, we recommend that you move to [EdgeLab Issues](https://github.com/Seeed-Studio/edgelab-model-zoo/issues) for faster assistance.

  - type: textarea
    id: issue-description
    attributes:
      label: Describe your issue
      description: A clear and concise description of what the problem is.
      placeholder: Issue description
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what it expected to be.
      placeholder: Expected behavior
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the bug report here (e.g. reproduce steps, package environment info or screenshots).

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read EdgeLab Model Zoo and EdgeLab docs.
          required: true
        - label: There has no simliar issue or pull request.
          required: true