name: verify-models

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/**'
      - 'requirements.txt'
      - 'scripts/**'
      - 'classification/models/**'
      - 'detection/models/**'
      - 'pose/models/**'

permissions:
  contents: read

jobs:
  checkout-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          ref: 'dev'

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Verify all model files (except '.pth')
        run: python3 scripts/verify_models.py
